# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

thinCpp <- function(l, D, n) {
    .Call('_thinr_thinCpp', PACKAGE = 'thinr', l, D, n)
}

